version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always

  web:
    build: ./web
    environment:
      MYSQL_HOST: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure